name: Release

on:
  push:
    tags:
      - "v*"

  release:
    types: [created]

jobs:
  publish-to-crateio:
    name: Publishing to crate.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [ crud-api-endpoint, crud-derive, crud-api-derive, crud-tidy-viewer, crud-auth, crud-auth-bearer, crud-auth-no-auth, crud-api, crud ]
    continue-on-error: true
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_API_KEY }} --no-verify -p ${{ matrix.package }}
