name: Release

on:
  push:
    tags:
      - "v*"

  release:
    types: [created]

jobs:
  publish-to-crate.io:
    name: Publishing to crate.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_API_KEY }} --allow-dirty
